# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: alertmanager-email-template
data:
  alerting_monitor_email.tmpl: |
    {{- (.Files.Get "files/emails/define") | nindent 4 }}{{ .Values.webUIAddress | trim }}{{.Files.Get "files/emails/end"}}
    {{- (.Files.Get "files/emails/define_o11y") | nindent 4 }}{{ .Values.observabilityUIAddress | trim }}{{.Files.Get "files/emails/end"}}
    {{- (.Files.Get "files/emails/define_mail") | nindent 4 }}
    {{- (.Files.Get "files/emails/email.html") | nindent 4 }}
    {{- (.Files.Get "files/emails/end") | nindent 4 }}
