# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
  # SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alerting-monitor-migrations
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
data:
{{- (.Files.Glob "files/atlas/migrations/*.sql").AsConfig | nindent 2 }}
