# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: alerting-monitor-management-allowed-traffic
  labels:
    {{- include "alerting-monitor-management.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.tenantController.namespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: observability-tenant-controller
      ports:
        - port: {{ include "alerting-monitor-management.ports.grpc" . }}
          protocol: TCP
  podSelector:
    matchLabels:
      {{- include "alerting-monitor-management.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
