# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.initialRules.init }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-rules
data: {{- tpl (.Files.Glob "files/rules/rules.yaml").AsConfig . | nindent 2 }}
{{- end -}}
