# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "alerting-monitor.labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "alerting-monitor.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-management
  labels:
    {{- include "alerting-monitor-management.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "alerting-monitor-management.ports.grpc" . }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "alerting-monitor-management.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-opa
  labels:
    {{- include "alerting-monitor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8181
      protocol: TCP
      name: opa
  selector:
    {{- include "alerting-monitor.selectorLabels" . | nindent 4 }}
---
# IngressRoute should only be installed when multitenant gateway is disabled.
{{- if not .Values.multitenantGatewayEnabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.traefik.gatewayNamespace }}
spec:
  entryPoints: # We listen to requests coming from ports 443
    - websecure
  routes:
    - match: {{ required "Traefik route match is required!" .Values.traefik.matchRoute }}
      kind: Rule
      middlewares:
        - name: validate-jwt
      services:
        - name: {{ .Chart.Name }}
          port: 8080
          scheme: http
          namespace: {{ .Release.Namespace }}
  tls:
    # Use the secret generated by cert-manager that resides in gateway-system namespace
    secretName: {{ .Values.traefik.secretName }}
{{- if .Values.traefik.tlsOption }}
    options:
      name: {{ .Values.traefik.tlsOption }}
      namespace: {{ .Values.traefik.gatewayNamespace }}
{{- end }}
{{- end }}
