# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alerting-monitor
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "networking.istio.io" ]
    resources: [ "serviceentries" ]
    verbs: [ "get", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "create", "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alerting-monitor
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: alerting-monitor
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: alerting-monitor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alerting-monitor
  namespace: {{ .Release.Namespace }}
