// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

package api //nolint:revive // Keep name as autogenerated

// TenantID defines model for tenant identifier.
type TenantID = string
