# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: smtp
  namespace: orch-infra
type: Opaque
stringData:
  smartHost: mailpit-svc.orch-infra.svc.cluster.local
  smartPort: "1025"
  from: Foo Bar <foo@bar.com>
  authUsername: foo@smtp.example.org
