# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: smtp-auth
  namespace: orch-infra
type: kubernetes.io/basic-auth
stringData:
  password: passpass
