# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: alerting-monitor
description: A Helm chart for Alerting Monitor
type: application
version: 1.7.2
appVersion: 1.7.2
annotations:
  revision: "762dd5f57bebb2d7b0ec1c54f202bb1726562bdf"
  created: "2025-06-03T08:48:30Z"
dependencies:
  - name: alertmanager
    condition: import.alertmanager.enabled
    version: "~1.14.0"
    repository: "https://prometheus-community.github.io/helm-charts"
