# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: alerting-monitor
description: A Helm chart for Alerting Monitor
type: application
version: 1.7.6
appVersion: 1.7.6
annotations:
  revision: "708d4a2be1f89899256e787631f7d7610ee866b0"
  created: "2026-02-18T12:25:24Z"
dependencies:
  - name: alertmanager
    condition: import.alertmanager.enabled
    version: "1.33.1"
    repository: "https://prometheus-community.github.io/helm-charts"
