# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: alerting-monitor
description: A Helm chart for Alerting Monitor
type: application
version: 1.9.4-obs
appVersion: 1.9.4-obs
annotations:
  revision: "21aa23b4409b85c90f3299b3861adfc3a0756639"
  created: "2025-05-28T08:40:44Z"
dependencies:
  - name: alertmanager
    condition: import.alertmanager.enabled
    version: "~1.14.0"
    repository: "https://prometheus-community.github.io/helm-charts"
