# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: alerting-monitor
description: A Helm chart for Alerting Monitor
type: application
version: 1.7.6
appVersion: 1.7.6
annotations:
  revision: "6b55bed2917a103daf5aba2b6667a8da8098c1ba"
  created: "2026-02-26T12:43:02Z"
dependencies:
  - name: alertmanager
    condition: import.alertmanager.enabled
    version: "1.33.1"
    repository: "https://prometheus-community.github.io/helm-charts"
