# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: alerting-monitor
description: A Helm chart for Alerting Monitor
type: application
version: 1.9.1-obs
appVersion: 1.9.1-obs
annotations:
  revision: "7074d7342c489bd2a2cc57d697f26d124cd8b87a"
  created: "2025-05-27T11:32:06Z"
dependencies:
  - name: alertmanager
    condition: import.alertmanager.enabled
    version: "~1.14.0"
    repository: "https://prometheus-community.github.io/helm-charts"
