# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: alerting-monitor
description: A Helm chart for Alerting Monitor
type: application
version: 1.7.4
appVersion: 1.7.4
annotations:
  revision: "167098330bdf012efa68aa76e927fdf5aa9d1f68"
  created: "2025-11-21T11:20:36Z"
dependencies:
  - name: alertmanager
    condition: import.alertmanager.enabled
    version: "1.29.0"
    repository: "https://prometheus-community.github.io/helm-charts"
