# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: alerting-monitor
description: A Helm chart for Alerting Monitor
type: application
version: 1.7.2-dev
appVersion: 1.7.2-dev
annotations:
  revision: "a59d913d76a3ff9a19cf36de1b9d94fef2f82563"
  created: "2025-05-28T10:04:07Z"
dependencies:
  - name: alertmanager
    condition: import.alertmanager.enabled
    version: "~1.14.0"
    repository: "https://prometheus-community.github.io/helm-charts"
