# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: alerting-monitor
description: A Helm chart for Alerting Monitor
type: application
version: 1.7.2
appVersion: 1.7.2
annotations:
  revision: "e54629bd1b21d0254411ede8e5ca9465403647ce"
  created: "2025-05-28T11:36:42Z"
dependencies:
  - name: alertmanager
    condition: import.alertmanager.enabled
    version: "~1.14.0"
    repository: "https://prometheus-community.github.io/helm-charts"
