# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: alerting-monitor
description: A Helm chart for Alerting Monitor
type: application
version: 1.8.1-log
appVersion: 1.8.1-log
annotations:
  revision: "444acb40cc89cd351e882e424cceeed253f0cfc3"
  created: "2025-05-26T10:20:13Z"
dependencies:
  - name: alertmanager
    condition: import.alertmanager.enabled
    version: "~1.14.0"
    repository: "https://prometheus-community.github.io/helm-charts"
