# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: alerting-monitor
description: A Helm chart for Alerting Monitor
type: application
version: 1.7.12
appVersion: 1.7.12
annotations:
  revision: "d777fc0eec0a724365b683d6980e7bc798897aa8"
  created: "2026-05-25T12:04:57Z"
dependencies:
  - name: alertmanager
    condition: import.alertmanager.enabled
    version: "1.36.0"
    repository: "https://prometheus-community.github.io/helm-charts"
