-- SPDX-FileCopyrightText: (C) 2025 Intel Corporation
-- SPDX-License-Identifier: Apache-2.0

-- Add new schema named "public"
CREATE SCHEMA IF NOT EXISTS "public";
-- Set comment to schema: "public"
COMMENT ON SCHEMA "public" IS 'standard public schema';
-- Create enum type "alert_definition_state"
CREATE TYPE "public"."alert_definition_state" AS ENUM ('New', 'Modified', 'Pending', 'Applied', 'Error');
-- Create enum type "receiver_state"
CREATE TYPE "public"."receiver_state" AS ENUM ('New', 'Modified', 'Pending', 'Applied', 'Error');
-- Create enum type "task_state"
CREATE TYPE "public"."task_state" AS ENUM ('New', 'Taken', 'Applied', 'Error', 'Invalid');
-- Create "alert_definitions" table
CREATE TABLE "public"."alert_definitions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "enabled" boolean NOT NULL,
  "uuid" uuid NOT NULL,
  "version" bigint NOT NULL,
  "name" text NOT NULL,
  "state" "public"."alert_definition_state" NOT NULL DEFAULT 'New',
  "template" text NULL,
  "category" text NULL,
  "context" text NULL,
  "severity" text NULL,
  "alert_interval" bigint NULL,
  "tenant_id" text NOT NULL DEFAULT 'edgenode',
  PRIMARY KEY ("id"),
  CONSTRAINT "alert_definitions_name_severity_version_tenant_key" UNIQUE ("name", "severity", "version", "tenant_id"),
  CONSTRAINT "alert_definitions_uuid_version_tenant_key" UNIQUE ("uuid", "version", "tenant_id")
);
-- Create "alert_durations" table
CREATE TABLE "public"."alert_durations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "duration" bigint NULL,
  "duration_min" bigint NULL,
  "duration_max" bigint NULL,
  "alert_definition_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "alert_durations_alert_definition_id_name_key" UNIQUE ("alert_definition_id", "name"),
  CONSTRAINT "alert_durations_alert_definition_id_fkey" FOREIGN KEY ("alert_definition_id") REFERENCES "public"."alert_definitions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "alert_thresholds" table
CREATE TABLE "public"."alert_thresholds" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "threshold" bigint NULL,
  "threshold_min" bigint NULL,
  "threshold_max" bigint NULL,
  "threshold_type" text NULL,
  "threshold_unit" text NULL,
  "alert_definition_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "alert_thresholds_alert_definition_id_name_key" UNIQUE ("alert_definition_id", "name"),
  CONSTRAINT "alert_thresholds_alert_definition_id_fkey" FOREIGN KEY ("alert_definition_id") REFERENCES "public"."alert_definitions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "email_addresses" table
CREATE TABLE "public"."email_addresses" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" text NOT NULL,
  "first_name" text NOT NULL,
  "last_name" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "email_addresses_email_key" UNIQUE ("email")
);
-- Create "email_configs" table
CREATE TABLE "public"."email_configs" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "mail_server" text NOT NULL,
  "from" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "email_configs_from_fkey" FOREIGN KEY ("from") REFERENCES "public"."email_addresses" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "receivers" table
CREATE TABLE "public"."receivers" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "uuid" uuid NOT NULL,
  "name" text NOT NULL,
  "state" "public"."receiver_state" NOT NULL DEFAULT 'New',
  "version" bigint NOT NULL,
  "email_config_id" bigint NOT NULL,
  "tenant_id" text NOT NULL DEFAULT 'edgenode',
  PRIMARY KEY ("id"),
  CONSTRAINT "receivers_name_version_tenant_key" UNIQUE ("name", "version", "tenant_id"),
  CONSTRAINT "receivers_uuid_version_tenant_key" UNIQUE ("uuid", "version", "tenant_id"),
  CONSTRAINT "receivers_email_config_id_fkey" FOREIGN KEY ("email_config_id") REFERENCES "public"."email_configs" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "email_recipients" table
CREATE TABLE "public"."email_recipients" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "receiver_id" bigint NOT NULL,
  "email_address_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "email_recipients_receiver_id_email_address_id_key" UNIQUE ("receiver_id", "email_address_id"),
  CONSTRAINT "email_recipients_email_address_id_fkey" FOREIGN KEY ("email_address_id") REFERENCES "public"."email_addresses" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "email_recipients_receiver_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES "public"."receivers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "tasks" table
CREATE TABLE "public"."tasks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "owner_uuid" uuid NULL,
  "state" "public"."task_state" NOT NULL DEFAULT 'New',
  "alert_definition_uuid" uuid NULL,
  "receiver_uuid" uuid NULL,
  "tenant_id" text NOT NULL DEFAULT 'edgenode',
  "version" bigint NULL,
  "creation_date" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "start_date" timestamp NULL,
  "completion_date" timestamp NULL,
  "retry_count" bigint NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "tasks_tenant_id_alert_definition_uuid_version_key" UNIQUE ("tenant_id", "alert_definition_uuid", "version"),
  CONSTRAINT "tasks_tenant_id_receiver_uuid_version_key" UNIQUE ("tenant_id", "receiver_uuid", "version"),
  CONSTRAINT "tasks_tenant_id_alert_definition_uuid_version_fkey" FOREIGN KEY ("tenant_id", "alert_definition_uuid", "version") REFERENCES "public"."alert_definitions" ("tenant_id", "uuid", "version") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "tasks_tenant_id_receiver_uuid_version_fkey" FOREIGN KEY ("tenant_id", "receiver_uuid", "version") REFERENCES "public"."receivers" ("tenant_id", "uuid", "version") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "tasks_check" CHECK (((alert_definition_uuid IS NULL) AND (receiver_uuid IS NOT NULL)) OR ((alert_definition_uuid IS NOT NULL) AND (receiver_uuid IS NULL)))
);
